// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//               'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//               'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyBk6J5EScndLq1KyJAOYonrIPc8LKvIyqs',
//     appId: '1:355891906558:web:7348eaedbaf27dc00562af',
//     messagingSenderId: '355891906558',
//     projectId: 'abeapplication-2b092',
//     authDomain: 'abeapplication-2b092.firebaseapp.com',
//     storageBucket: 'abeapplication-2b092.appspot.com',
//     measurementId: 'G-FPLNYWWLMH',
//   );
//
//   static const FirebaseOptions android = FirebaseOptions(
//       apiKey: "AIzaSyAHDtPdDL2sg_DDhqj6nQJA66OFAZM-Z2s",
//       authDomain: "brainboosters-6d9a1.firebaseapp.com",
//       projectId: "brainboosters-6d9a1",
//       storageBucket: "brainboosters-6d9a1.appspot.com",
//       messagingSenderId: "852632874780",
//       appId: "1:852632874780:web:ee1da32c4b02425dae94d9"
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyBGlWf-_SckKCAccOAKBlKtUmN7tcSm2cg',
//     appId: '1:355891906558:ios:5ebbd1ca1be8690e0562af',
//     messagingSenderId: '355891906558',
//     projectId: 'abeapplication-2b092',
//     storageBucket: 'abeapplication-2b092.appspot.com',
//     iosClientId: '355891906558-o7arn17dto6at83ok3catecs7omima1f.apps.googleusercontent.com',
//     iosBundleId: 'com.example.abe',
//   );
//
//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyBGlWf-_SckKCAccOAKBlKtUmN7tcSm2cg',
//     appId: '1:355891906558:ios:5ebbd1ca1be8690e0562af',
//     messagingSenderId: '355891906558',
//     projectId: 'abeapplication-2b092',
//     storageBucket: 'abeapplication-2b092.appspot.com',
//     iosClientId: '355891906558-o7arn17dto6at83ok3catecs7omima1f.apps.googleusercontent.com',
//     iosBundleId: 'com.example.abe',
//   );
// }